[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
{% if license == "MIT" -%}
license = "MIT"
{% endif -%}
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
